DROP DATABASE IF EXISTS indoorGyms;

CREATE DATABASE indoorGyms;

USE indoorGyms;

CREATE TABLE Countries(
  CountryName VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE Gyms(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  GymName VARCHAR(80) NOT NULL,
  Link VARCHAR(270) NOT NULL,
  Region VARCHAR(100),
  Website VARCHAR(270),
  Phone VARCHAR(40),
  GymAddress VARCHAR(200),
  Subregion VARCHAR(50),
  Rating DECIMAL(2,1),
  Country VARCHAR(50),
  FOREIGN KEY (Country) REFERENCES Countries(CountryName)
);

-- CREATE TABLE Keys(
--   Id INT AUTO_INCREMENT PRIMARY KEY,
--   key VARCHAR(36)
-- );

CREATE TABLE Users(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(36),
  Salt INT,
);
